# https://circleci.com/docs/2.0/configuration-reference/, for more  info on how to get started.

version: 2.1

orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    steps:
      - checkout
      - run:
          name: Install bundler
          command: gem install bundler -v '2.0.2'
      - ruby/bundle-install
      - run:
          name: Run rspec tests
          command: bundle exec rake spec
