---
:production:
  :concurrency: 10
  :subscriptions:
  - :name: notifications
    :ratio: 10
  - :name: "heartbeat/#"
    :ratio: 10
  :mqtt:
    - :host: localhost
      :port: 1833
      :ssl: false
      :cert_file: ''
      :key_file: ''
      :ca_file: ''
